### ISSUE TITLE
ValueError: Could not find device 'Bantersaurus'

### ISSUE THREAD

**Issue by seahkahyen** [LooseLab/Icarust#15]
Hello!
I am trying to run readfish with Icarust and I cant seem to fix this error: 
2024-05-30 17:49:24,430 readfish /home/kahyen/miniforge3/bin/readfish targets --port 10000 --toml test.toml --device Bantersaurus --log-file test.log --experiment-name select_one_bac
2024-05-30 17:49:24,430 readfish chemistry=<Chemistry.SIMPLEX: 'simplex'>
2024-05-30 17:49:24,430 readfish command='targets'
2024-05-30 17:49:24,430 readfish debug_log=True
2024-05-30 17:49:24,430 readfish device='Bantersaurus'
2024-05-30 17:49:24,431 readfish dry_run=False
2024-05-30 17:49:24,431 readfish experiment_name='select_one_bac'
2024-05-30 17:49:24,431 readfish host='127.0.0.1'
2024-05-30 17:49:24,431 readfish log_file='test.log'
2024-05-30 17:49:24,431 readfish log_format='%(asctime)s %(name)s %(message)s'
2024-05-30 17:49:24,431 readfish log_level='info'
2024-05-30 17:49:24,431 readfish max_unblock_read_length_seconds=5
2024-05-30 17:49:24,432 readfish padding=0
2024-05-30 17:49:24,432 readfish port='10000'
2024-05-30 17:49:24,432 readfish throttle=0.4
2024-05-30 17:49:24,432 readfish toml='test.toml'
2024-05-30 17:49:24,432 readfish unblock_duration=0.1
2024-05-30 17:49:24,432 readfish wait_for_ready=120
2024-05-30 17:49:24,432 readfish Version=2024.2.0
Traceback (most recent call last):
  File "/home/kahyen/miniforge3/bin/readfish", line 8, in <module>
    sys.exit(main())
  File "/home/kahyen/miniforge3/lib/python3.10/site-packages/readfish/_cli_base.py", line 61, in main
    raise SystemExit(args.func(parser, args, extras))
  File "/home/kahyen/miniforge3/lib/python3.10/site-packages/readfish/entry_points/targets.py", line 604, in run
    position = get_device(args.device, host=args.host, port=args.port)
  File "/home/kahyen/miniforge3/lib/python3.10/site-packages/readfish/_utils.py", line 451, in get_device
    raise ValueError(f"Could not find device {device!r}")
ValueError: Could not find device 'Bantersaurus'

I have already run this in the command: 
cargo run --release -- --help
export MINKNOW_TRUSTED_CA="static/tls_certs/ca.crt"
readfish targets --port 10000 --toml test.toml --device 'Bantersaurus' --log-file test.log --experiment-name select_one_bac

How do I fix this error? Thank you so much for any help in advance!

**Comment by Adoni5** [comment]
Hi @seahkahyen, thanks for giving Icarust a go!

It looks like you are very close, `readfish` connected to Icarust, and is looking for a position on the "sequencer", but can't find it.

Can I ask what Icarust command you ran, and what is in the profile simulation TOML file which you used?

Cheers,
Rory

**Comment by Adoni5** [comment]
Hey @seahkahyen - any joy?

Can you show me the contents of the `config.ini` file? I've not seen error code 8 before!

Rory

**Comment by Adoni5** [comment]
Okay there's a couple of things to try - can you first change 
```ini
[SEQUENCER]
channels = 96
```

```ini
[SEQUENCER]
channels = 512
```
And try running `readfish unblock-all --port 13000  --device Bantersaurus --log-file test.log --experiment-name test`.

This should be a good test for connecting that will avoid having to base-call and align. 
As a side note, if the caller settings in you `readfish` TOML are noop, your aligner will not align anything as there won't be any base-called data!

Cheers,
Rory

**Comment by Adoni5** [comment]
This is strange! Can I ask what `Icarust` is logging to the screen at the time that `readfish` is connecting/throwing this error?

I'm going to prepare a minimal working example script outside of `readfish` which should be easier to debug.
